node.name = emqx@127.0.0.1
allow_anonymous = true

listener.tcp.external = 0.0.0.0:1883
listener.ws.external = 0.0.0.0:8083

dashboard.listener.http = 18083
dashboard.default_user.login = admin
dashboard.default_user.password = public